.PHONY: clean All

All:
	@echo "----------Building project:[ Adriano - Debug ]----------"
	@$(MAKE) -f  "Adriano.mk"
clean:
	@echo "----------Cleaning project:[ Adriano - Debug ]----------"
	@$(MAKE) -f  "Adriano.mk" clean
